// Mock data for demo purposes when backend is not available

export const mockCourses = [
  {
    course_id: 1,
    title: 'Complete Web Development Bootcamp 2026',
    description: 'Learn HTML, CSS, JavaScript, React, Node.js and build real-world projects. Perfect for beginners who want to become professional web developers.',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=500&h=300&fit=crop',
    instructor_name: 'Dr. Karim Rahman',
    difficulty_level: 'beginner',
    duration_hours: 45,
    price: 3500,
    is_published: true,
    enrollment_count: 1247,
    category: 'Web Development',
  },
  {
    course_id: 2,
    title: 'Data Science with Python',
    description: 'Master data analysis, visualization, and machine learning using Python, Pandas, NumPy, and Scikit-learn. Includes real datasets and projects.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop',
    instructor_name: 'Prof. Ayesha Siddiqui',
    difficulty_level: 'intermediate',
    duration_hours: 60,
    price: 4500,
    is_published: true,
    enrollment_count: 892,
    category: 'Data Science',
  },
  {
    course_id: 3,
    title: 'Mobile App Development with React Native',
    description: 'Build cross-platform mobile applications for iOS and Android using React Native. Learn navigation, APIs, and deployment.',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500&h=300&fit=crop',
    instructor_name: 'Eng. Rahim Ahmed',
    difficulty_level: 'intermediate',
    duration_hours: 35,
    price: 4000,
    is_published: true,
    enrollment_count: 654,
    category: 'Mobile Development',
  },
  {
    course_id: 4,
    title: 'Digital Marketing Masterclass',
    description: 'Complete guide to SEO, social media marketing, Google Ads, email marketing, and content strategy for Bangladesh market.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=300&fit=crop',
    instructor_name: 'Tasnim Haque',
    difficulty_level: 'beginner',
    duration_hours: 25,
    price: 0,
    is_published: true,
    enrollment_count: 2103,
    category: 'Marketing',
  },
  {
    course_id: 5,
    title: 'Advanced JavaScript & ES6+',
    description: 'Deep dive into modern JavaScript: async/await, promises, modules, closures, and advanced ES6+ features. For experienced developers.',
    thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=500&h=300&fit=crop',
    instructor_name: 'Abdullah Khan',
    difficulty_level: 'advanced',
    duration_hours: 30,
    price: 2500,
    is_published: true,
    enrollment_count: 431,
    category: 'Programming',
  },
  {
    course_id: 6,
    title: 'UI/UX Design Fundamentals',
    description: 'Learn design principles, Figma, user research, wireframing, prototyping, and create stunning user interfaces.',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
    instructor_name: 'Nusrat Jahan',
    difficulty_level: 'beginner',
    duration_hours: 28,
    price: 0,
    is_published: true,
    enrollment_count: 1567,
    category: 'Design',
  },
];

export const mockCourseDetail = {
  course_id: 1,
  title: 'Complete Web Development Bootcamp 2026',
  description: 'Learn HTML, CSS, JavaScript, React, Node.js and build real-world projects.',
  thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop',
  instructor_name: 'Dr. Karim Rahman',
  difficulty_level: 'beginner',
  duration_hours: 45,
  price: 3500,
  modules: [
    {
      module_id: 1,
      title: 'Getting Started with Web Development',
      order_index: 1,
      lessons: [
        {
          lesson_id: 1,
          title: 'Welcome to the Course',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
          duration_minutes: 12,
          order_index: 1,
          is_completed: false,
        },
        {
          lesson_id: 2,
          title: 'Setting Up Your Development Environment',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
          duration_minutes: 18,
          order_index: 2,
          is_completed: false,
        },
        {
          lesson_id: 3,
          title: 'Course Resources and Materials',
          content_type: 'reading',
          content: '<h2>Course Resources</h2><p>Welcome to the Web Development Bootcamp! Here you will find all the resources you need.</p><ul><li>Code editor: VS Code</li><li>Browser: Chrome or Firefox</li><li>Git installed</li></ul>',
          duration_minutes: 5,
          order_index: 3,
          is_completed: false,
        },
      ],
      quizzes: [
        {
          quiz_id: 1,
          title: 'Module 1 Assessment',
          module_id: 1,
        },
      ],
    },
    {
      module_id: 2,
      title: 'HTML & CSS Fundamentals',
      order_index: 2,
      lessons: [
        {
          lesson_id: 4,
          title: 'HTML Basics - Elements and Tags',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=pQN-pnXPaVg',
          duration_minutes: 25,
          order_index: 1,
          is_completed: false,
        },
        {
          lesson_id: 5,
          title: 'CSS Styling and Selectors',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=1PnVor36_40',
          duration_minutes: 30,
          order_index: 2,
          is_completed: false,
        },
        {
          lesson_id: 6,
          title: 'Building Your First Webpage',
          content_type: 'case_study',
          content: '<h2>Project: Personal Portfolio</h2><p>In this hands-on project, you will build a complete personal portfolio website.</p><h3>Requirements:</h3><ul><li>Header with navigation</li><li>About section</li><li>Projects gallery</li><li>Contact form</li><li>Responsive design</li></ul>',
          duration_minutes: 45,
          order_index: 3,
          is_completed: false,
        },
      ],
      quizzes: [
        {
          quiz_id: 2,
          title: 'HTML & CSS Quiz',
          module_id: 2,
        },
      ],
    },
    {
      module_id: 3,
      title: 'JavaScript Programming',
      order_index: 3,
      lessons: [
        {
          lesson_id: 7,
          title: 'JavaScript Variables and Data Types',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=W6NZfCO5SIk',
          duration_minutes: 22,
          order_index: 1,
          is_completed: false,
        },
        {
          lesson_id: 8,
          title: 'Functions and Scope',
          content_type: 'video',
          video_url: 'https://www.youtube.com/watch?v=N8ap4k_1QEQ',
          duration_minutes: 28,
          order_index: 2,
          is_completed: false,
        },
      ],
      quizzes: [],
    },
  ],
};

export const mockQuiz = {
  quiz_id: 1,
  title: 'Module 1 Assessment - Getting Started',
  description: 'Test your understanding of web development basics and development environment setup.',
  time_limit_minutes: 15,
  passing_score: 70,
  max_attempts: 3,
  total_points: 100,
  questions: [
    {
      question_id: 1,
      question_text: 'What does HTML stand for?',
      question_type: 'multiple_choice',
      points: 5,
      options: [
        { id: 'a', text: 'Hyper Text Markup Language' },
        { id: 'b', text: 'High Tech Modern Language' },
        { id: 'c', text: 'Home Tool Markup Language' },
        { id: 'd', text: 'Hyperlinks and Text Markup Language' },
      ],
      correct_answer: 'a',
      explanation: 'HTML stands for Hyper Text Markup Language, which is the standard markup language for creating web pages.',
    },
    {
      question_id: 2,
      question_text: 'CSS is used for styling web pages.',
      question_type: 'true_false',
      points: 5,
      correct_answer: 'true',
      explanation: 'CSS (Cascading Style Sheets) is indeed used for styling and layout of web pages.',
    },
    {
      question_id: 3,
      question_text: 'Which code editor is recommended for this course?',
      question_type: 'multiple_choice',
      points: 5,
      options: [
        { id: 'a', text: 'Notepad' },
        { id: 'b', text: 'VS Code' },
        { id: 'c', text: 'MS Word' },
        { id: 'd', text: 'Excel' },
      ],
      correct_answer: 'b',
      explanation: 'Visual Studio Code (VS Code) is the recommended code editor for this course.',
    },
    {
      question_id: 4,
      question_text: 'JavaScript is only used for backend development.',
      question_type: 'true_false',
      points: 5,
      correct_answer: 'false',
      explanation: 'JavaScript is used for both frontend and backend development (with Node.js).',
    },
  ],
};

export const mockDiscussions = [
  {
    discussion_id: 1,
    module_id: 1,
    user_id: 1,
    title: 'How to install VS Code on Windows?',
    content: '<p>I am having trouble installing VS Code on my Windows 10 machine. Can someone help?</p>',
    is_qa: true,
    is_resolved: true,
    author_name: 'Fahim Ahmed',
    author_role: 'student',
    created_at: '2026-01-25T10:30:00',
    reply_count: 3,
  },
  {
    discussion_id: 2,
    module_id: 1,
    user_id: 2,
    title: 'Best resources for learning HTML/CSS?',
    content: '<p>Besides this course, what other resources would you recommend for mastering HTML and CSS?</p>',
    is_qa: false,
    is_resolved: false,
    author_name: 'Sadia Rahman',
    author_role: 'student',
    created_at: '2026-01-26T14:20:00',
    reply_count: 5,
  },
  {
    discussion_id: 3,
    module_id: 2,
    user_id: 3,
    title: 'Difference between padding and margin?',
    content: '<p>I am confused about when to use padding vs margin in CSS. Can someone explain?</p>',
    is_qa: true,
    is_resolved: true,
    author_name: 'Rakib Hasan',
    author_role: 'student',
    created_at: '2026-01-27T09:15:00',
    reply_count: 2,
  },
];

export const mockDiscussionDetail = {
  discussion_id: 1,
  module_id: 1,
  user_id: 1,
  title: 'How to install VS Code on Windows?',
  content: '<p>I am having trouble installing VS Code on my Windows 10 machine. The installer keeps giving me an error. Can someone help?</p>',
  is_qa: true,
  is_resolved: true,
  author_name: 'Fahim Ahmed',
  author_role: 'student',
  created_at: '2026-01-25T10:30:00',
  replies: [
    {
      reply_id: 1,
      discussion_id: 1,
      user_id: 4,
      content: '<p>Try downloading from the official website: <a href="https://code.visualstudio.com">https://code.visualstudio.com</a></p><p>Make sure to run the installer as administrator.</p>',
      author_name: 'Nadia Khan',
      is_instructor_reply: false,
      created_at: '2026-01-25T11:00:00',
    },
    {
      reply_id: 2,
      discussion_id: 1,
      user_id: 100,
      content: '<p>Also check if you have enough disk space and your antivirus is not blocking the installation.</p><p>If the issue persists, you can try the portable version of VS Code which doesn\'t require installation.</p>',
      author_name: 'Dr. Karim Rahman',
      is_instructor_reply: true,
      created_at: '2026-01-25T15:30:00',
    },
    {
      reply_id: 3,
      discussion_id: 1,
      user_id: 1,
      content: '<p>Thanks everyone! Running as administrator solved the issue. VS Code is now installed successfully!</p>',
      author_name: 'Fahim Ahmed',
      is_instructor_reply: false,
      created_at: '2026-01-25T16:45:00',
    },
  ],
};

export const mockAnalytics = {
  totalStudents: 6894,
  totalRevenue: 12450000,
  totalCourses: 6,
  avgCompletionRate: 68,
  enrollmentTrend: [
    { month: 'Aug', enrollments: 412 },
    { month: 'Sep', enrollments: 578 },
    { month: 'Oct', enrollments: 691 },
    { month: 'Nov', enrollments: 834 },
    { month: 'Dec', enrollments: 1123 },
    { month: 'Jan', enrollments: 1456 },
  ],
  progressDistribution: [
    { name: '0-25%', value: 22 },
    { name: '26-50%', value: 28 },
    { name: '51-75%', value: 32 },
    { name: '76-100%', value: 18 },
  ],
  activeUsers: [
    { day: 'Mon', users: 234 },
    { day: 'Tue', users: 267 },
    { day: 'Wed', users: 245 },
    { day: 'Thu', users: 312 },
    { day: 'Fri', users: 289 },
    { day: 'Sat', users: 198 },
    { day: 'Sun', users: 156 },
  ],
};

export const mockUser = {
  user_id: 1,
  email: 'demo@edtech.bd',
  name: 'Demo User',
  role: 'student',
};

export const mockInstructor = {
  user_id: 100,
  email: 'instructor@edtech.bd',
  name: 'Dr. Karim Rahman',
  role: 'instructor',
};
